import { DemoState } from "./types";

const DEMO_NOW_MS = Date.parse("2026-03-22T19:00:00.000Z");

export const demoState: DemoState = {
  nowMs: DEMO_NOW_MS,
  vault: {
    id: "guards-vault-001",
    name: "RBTC Core Reserve",
    chain: "evm",
    stage: "normal",
    ladderStep: "auto_reentry",
    signers: ["0x9cF3...governance"],
    keepers: ["0x4a11...operator"],
  },
  positions: [
    {
      assetId: "rbtc",
      symbol: "RBTC",
      role: "risk",
      amount: 0.825,
      fiatValue: 56099.19,
      weight: 0.6,
    },
    {
      assetId: "doc",
      symbol: "DOC",
      role: "stable",
      amount: 36000,
      fiatValue: 36000,
      weight: 0.4,
    },
  ],
  oracle: {
    feedId: "market-rbtc-usd",
    symbol: "RBTC/USD",
    price: 67878.41,
    emaPrice: 68220.55,
    confidence: 48.21,
    publisherCount: 0,
    updatedAtMs: DEMO_NOW_MS - 2_000,
  },
  policy: {
    policyId: "guards-policy-001",
    primaryAssetId: "rbtc",
    primaryFeedId: "market-rbtc-usd",
    stableAssetId: "doc",
    approvedRouteIds: ["rootstock-sovryn-rbtc-doc"],
    portfolioFloorFiat: 78000,
    emergencyPortfolioFloorFiat: 70000,
    haircutBps: 150,
    maxStaleUs: 30_000_000,
    maxConfidenceBps: 200,
    cooldownUs: 600_000_000,
    watchDrawdownBps: 300,
    partialDrawdownBps: 700,
    fullExitDrawdownBps: 1200,
    reentryDrawdownBps: -500,
    partialStableTargetRatio: 0.5,
    reentryRiskTargetRatio: 0.6,
  },
  events: [
    {
      id: "evt-001",
      kind: "derisk_swap",
      stage: "partial_derisk",
      sourceSymbol: "RBTC",
      destinationSymbol: "DOC",
      amount: 0.12,
      route: "rootstock-sovryn-rbtc-doc",
      timestamp: DEMO_NOW_MS - 3_600_000,
      status: "executed",
    },
    {
      id: "evt-002",
      kind: "derisk_swap",
      stage: "full_exit",
      sourceSymbol: "RBTC",
      destinationSymbol: "DOC",
      amount: 0.28,
      route: "rootstock-sovryn-rbtc-doc",
      timestamp: DEMO_NOW_MS - 1_800_000,
      status: "executed",
    },
    {
      id: "evt-003",
      kind: "reentry_swap",
      stage: "normal",
      sourceSymbol: "DOC",
      destinationSymbol: "RBTC",
      amount: 8000,
      route: "rootstock-moc-doc-rbtc",
      timestamp: DEMO_NOW_MS - 600_000,
      status: "pending",
    },
  ],
  metrics: {
    liquidValue: 91257.7,
    stableRatio: 0.3945,
    drawdownBps: 50,
    oracleFreshness: "demo snapshot",
  },
  frames: [
    {
      index: 0,
      balance: 100000,
      stableRatio: 0.2,
      stage: "normal",
      trigger: "Initial state",
      explanation: "Treasury operating within normal parameters.",
    },
    {
      index: 1,
      balance: 96000,
      stableRatio: 0.2,
      stage: "watch",
      trigger: "Drawdown > 300bps",
      explanation:
        "RBTC weakens versus the treasury baseline. Operators enter watch mode and review allowed actions.",
    },
    {
      index: 2,
      balance: 91000,
      stableRatio: 0.45,
      stage: "partial_derisk",
      trigger: "Drawdown > 700bps",
      explanation:
        "A bounded treasury action shifts part of the RBTC reserve into DOC to defend operating coverage.",
    },
    {
      index: 3,
      balance: 85000,
      stableRatio: 0.85,
      stage: "full_exit",
      trigger: "Drawdown > 1200bps / Floor breached",
      explanation:
        "Treasury protection mode escalates and exits most risk exposure into DOC.",
    },
    {
      index: 4,
      balance: 93750,
      stableRatio: 0.4,
      stage: "normal",
      trigger: "Recovery > 500bps",
      explanation:
        "Price recovered past re-entry threshold. Auto re-entry restored risk allocation.",
    },
  ],
};
